pipeline {
  agent any
  tools { 
    nodejs 'node26' // Jenkins > Global Tool Config: NodeJS named "node26"
     allure 'allure'// Jenkins > Global Tool Config: Allure named "allure"
    }
    options {
    timeout(time: 20, unit: 'MINUTES') // To prevent running for long time
  }
  // Binds TEST_CREDS_USR and TEST_CREDS_PSW
  environment { 
    TEST_CREDS = credentials('e2e-test-user') 
     PLAYWRIGHT_BROWSERS_PATH = '0'
      // To ensure browsers are installed in the workspace and not shared globally
    }
  // -eu: shell safety setting (e -Exit immediately if any command fails; u- Treat unset variables as errors.)
  stages {
    stage('Build') {
     
      steps {
        bat '''
            if exist node_modules rmdir /s /q node_modules
          set PLAYWRIGHT_BROWSERS_PATH=0
          npm ci
          echo Installing Playwright browsers...
          call npx playwright install --with-deps
          echo Playwright install completed
        '''
      }
    }
    stage('Verify Browsers') {
    steps {
        bat '''
            set PLAYWRIGHT_BROWSERS_PATH=0
            echo Checking Playwright browser cache...
            dir node_modules\\playwright-core\\.local-browsers /s 2>nul || (
              echo.
              echo ERROR: Browser cache not found
              echo Listing node_modules contents:
              dir node_modules /b
              exit /b 1
            )
        '''
    }
}
    stage('Run Tests') {
      steps {
        bat '''
          set PLAYWRIGHT_BROWSERS_PATH=0
          echo Ensuring browsers are ready before running tests...
          npx playwright install --with-deps
          set TEST_USER_NAME=%TEST_CREDS_USR%
          set TEST_PASSWORD=%TEST_CREDS_PSW%
          npm run testenv:myapp
        '''
      }
    
      post {
        always {
             archiveArtifacts artifacts: 'playwright-report/**', fingerprint: true
         // Publish Allure results generated by the test run
          allure includeProperties: false,
                 jdk: '',
                 results: [[path: 'allure-results']],
                 reportBuildPolicy: 'ALWAYS'
        }
      }
    }
  }
}