pipeline {
  agent any
  tools { 
    nodejs 'node26' // Jenkins > Global Tool Config: NodeJS named "node26"
     allure 'allure'// Jenkins > Global Tool Config: Allure named "allure"
    }
    options {
    timeout(time: 60, unit: 'MINUTES') // Increased to allow browser download and extraction
  }
  // Binds TEST_CREDS_USR and TEST_CREDS_PSW
  environment { 
    TEST_CREDS = credentials('e2e-test-user') 
     PLAYWRIGHT_BROWSERS_PATH = '0'
      // To ensure browsers are installed in the workspace and not shared globally
    }
  // -eu: shell safety setting (e -Exit immediately if any command fails; u- Treat unset variables as errors.)
  stages {
    stage('Build') {
     
      steps {
        bat 'if exist node_modules rmdir /s /q node_modules'
        bat 'set PLAYWRIGHT_BROWSERS_PATH=0 && npm ci'
        bat 'set PLAYWRIGHT_BROWSERS_PATH=0 && set DEBUG=pw:install && npx playwright install --with-deps'
      }
    }
    stage('Verify Browsers') {
    steps {
        bat 'set PLAYWRIGHT_BROWSERS_PATH=0 && dir node_modules\\playwright-core\\.local-browsers'
    }
}
    stage('Run Tests') {
      steps {
        bat 'set PLAYWRIGHT_BROWSERS_PATH=0 && set TEST_USER_NAME=%TEST_CREDS_USR% && set TEST_PASSWORD=%TEST_CREDS_PSW% && npm run testenv:myapp'
      }
    
      post {
        always {
             archiveArtifacts artifacts: 'playwright-report/**', fingerprint: true
         // Publish Allure results generated by the test run
          allure includeProperties: false,
                 jdk: '',
                 results: [[path: 'allure-results']],
                 reportBuildPolicy: 'ALWAYS'
        }
      }
    }
  }
}